### ISSUE TITLE
Change size on CheckBox

### ISSUE THREAD

**Issue by hundsim** [thenativeweb/thenativeweb-ux#5]
Is it be possible to change size on the CheckBox component?

I tried with no success: https://codesandbox.io/s/k0pn7zx4oo

**Comment by goloroden** [comment]
I think @mattwagl would need to answer this, but right now he's on vacation. Once he's back, he will get back to you (I just wanted to let you know so that you don't wait and wait, and wonder why nobody is replying).

**Comment by mattwagl** [comment]
@hundsim At the moment it's not possible to set the `style` option on this component. That's why the transform is not applied. You can however use the `className` property to add a class and apply the styles via CSS. See https://codesandbox.io/s/p7j7yk63jm

I'm a bit unsure if we sould allow local styles on components. We're trying to avoid this as much as possible. But I'll take this question to our next sprint that starts next week. :-)

**Comment by mattwagl** [comment]
With  version `0.8.1` this is now posssible – see https://codesandbox.io/s/y0okrl9829. So I'm going to close this issue.
